export const FRIDAY = [
  {
    index: 47,
    start: "15:55",
    end: "16:25",
    band: "Broken By The Scream",
    stage: "main",
  },
  {
    index: 48,
    start: "17:05",
    end: "17:50",
    band: "Deviloof",
    stage: "main",
  },
  {
    index: 49,
    start: "18:40",
    end: "19:30",
    band: "Aphonnic",
    stage: "main",
  },
  {
    index: 50,
    start: "20:30",
    end: "21:45",
    band: "Tesseract",
    stage: "main",
  },
  {
    index: 51,
    start: "23:00",
    end: "00:15",
    band: "Falling In Reverse",
    stage: "main",
  },
  {
    index: 52,
    start: "01:20",
    end: "02:35",
    band: "Angelus Apatrida",
    stage: "main",
  },
  {
    index: 53,
    start: "15:05",
    end: "15:45",
    band: "Against The Waves",
    stage: "ritual",
  },
  {
    index: 54,
    start: "16:25",
    end: "17:05",
    band: "Party Cannon",
    stage: "ritual",
  },
  {
    index: 55,
    start: "17:50",
    end: "18:40",
    band: "Unprocessed",
    stage: "ritual",
  },
  {
    index: 56,
    start: "19:30",
    end: "20:30",
    band: "Soen",
    stage: "ritual",
  },
  {
    index: 57,
    start: "21:45",
    end: "22:45",
    band: "Crucified Barbara",
    stage: "ritual",
  },
  {
    index: 58,
    start: "00:20",
    end: "01:20",
    band: "Stesy",
    stage: "ritual",
  },
  {
    index: 59,
    start: "15:45",
    end: "16:25",
    band: "Prom Kinks",
    stage: "chaos",
  },
  {
    index: 60,
    start: "17:05",
    end: "17:50",
    band: "Blackgold",
    stage: "chaos",
  },
  {
    index: 61,
    start: "18:40",
    end: "19:30",
    band: "Sound of Silence",
    stage: "chaos",
  },
  {
    index: 62,
    start: "20:10",
    end: "21:10",
    band: "Anal Hard",
    stage: "chaos",
  },
  {
    index: 63,
    start: "21:50",
    end: "22:50",
    band: "Lake Malice",
    stage: "chaos",
  },
  {
    index: 64,
    start: "23:30",
    end: "00:20",
    band: "Desolated",
    stage: "chaos",
  },
  {
    index: 65,
    start: "01:25",
    end: "02:35",
    band: "Ignite",
    stage: "chaos",
  },
  {
    index: 66,
    start: "15:05",
    end: "15:40",
    band: "Your Knife My Back",
    stage: "desert",
  },
  {
    index: 67,
    start: "16:20",
    end: "17:05",
    band: "Moonshine Wagon",
    stage: "desert",
  },
  {
    index: 68,
    start: "17:45",
    end: "18:35",
    band: "Datcha Mandala",
    stage: "desert",
  },
  {
    index: 69,
    start: "19:15",
    end: "20:05",
    band: "Slow Crush",
    stage: "desert",
  },
  {
    index: 70,
    start: "20:45",
    end: "21:45",
    band: "Tabernis",
    stage: "desert",
  },
  {
    index: 71,
    start: "22:40",
    end: "23:40",
    band: "Derby Motoreta’s Burrito Kachimba",
    stage: "desert",
  },
  {
    index: 72,
    start: "00:20",
    end: "01:30",
    band: "Harakiri For The Sky",
    stage: "desert",
  },
];
