export const SATURDAY = [
  {
    index: 73,
    start: "16:10",
    end: "16:50",
    band: "Gutalax",
    stage: "main",
  },
  {
    index: 74,
    start: "17:35",
    end: "18:20",
    band: "Tetrarch",
    stage: "main",
  },
  {
    index: 75,
    start: "19:10",
    end: "19:55",
    band: "Aviana",
    stage: "main",
  },
  {
    index: 76,
    start: "20:45",
    end: "21:45",
    band: "Crossfaith",
    stage: "main",
  },
  {
    index: 77,
    start: "23:00",
    end: "00:30",
    band: "Slipknot",
    stage: "main",
  },
  {
    index: 78,
    start: "01:45",
    end: "03:00",
    band: "Skindred",
    stage: "main",
  },
  {
    index: 79,
    start: "15:35",
    end: "16:10",
    band: "Our Natural Killer",
    stage: "ritual",
  },
  {
    index: 80,
    start: "16:50",
    end: "17:35",
    band: "The Broken Horizon",
    stage: "ritual",
  },
  {
    index: 81,
    start: "18:20",
    end: "19:10",
    band: "Mental Cruelty",
    stage: "ritual",
  },
  {
    index: 82,
    start: "19:55",
    end: "20:45",
    band: "Spectral Wound",
    stage: "ritual",
  },
  {
    index: 83,
    start: "21:45",
    end: "22:45",
    band: "Vader",
    stage: "ritual",
  },
  {
    index: 84,
    start: "00:45",
    end: "01:45",
    band: "Zeal & Ardor",
    stage: "ritual",
  },
  {
    index: 85,
    start: "15:35",
    end: "16:15",
    band: "Archivo Adxunto",
    stage: "chaos",
  },
  {
    index: 86,
    start: "16:50",
    end: "17:40",
    band: "Pintglass",
    stage: "chaos",
  },
  {
    index: 87,
    start: "18:20",
    end: "19:10",
    band: "Iscream Never Ground",
    stage: "chaos",
  },
  {
    index: 88,
    start: "19:55",
    end: "20:45",
    band: "Split Chain",
    stage: "chaos",
  },
  {
    index: 89,
    start: "21:40",
    end: "22:50",
    band: "Walls of Jericho",
    stage: "chaos",
  },
  {
    index: 90,
    start: "23:30",
    end: "00:30",
    band: "Siamese",
    stage: "chaos",
  },
  {
    index: 91,
    start: "01:20",
    end: "02:20",
    band: "ten56.",
    stage: "chaos",
  },
  {
    index: 92,
    start: "16:10",
    end: "16:50",
    band: "Saturna",
    stage: "desert",
  },
  {
    index: 93,
    start: "17:30",
    end: "18:20",
    band: "Dirty Sound Magnet",
    stage: "desert",
  },
  {
    index: 94,
    start: "19:05",
    end: "19:50",
    band: "Slomosa",
    stage: "desert",
  },
  {
    index: 95,
    start: "20:35",
    end: "21:45",
    band: "Russian Circles",
    stage: "desert",
  },
  {
    index: 96,
    start: "23:00",
    end: "00:00",
    band: "And So I Watch You From Afar",
    stage: "desert",
  },
];
