export const THURSDAY = [
  {
    index: 24,
    start: "15:45",
    end: "16:25",
    band: "Stain The Canvas",
    stage: "main",
  },
  {
    index: 25,
    start: "17:05",
    end: "17:55",
    band: "Northlane",
    stage: "main",
  },
  {
    index: 26,
    start: "18:45",
    end: "19:35",
    band: "Seven Hours After Violet",
    stage: "main",
  },
  {
    index: 27,
    start: "20:35",
    end: "22:05",
    band: "Till Lindemann",
    stage: "main",
  },
  {
    index: 28,
    start: "23:30",
    end: "01:00",
    band: "KoRn",
    stage: "main",
  },
  {
    index: 29,
    start: "15:05",
    end: "15:45",
    band: "Killus",
    stage: "ritual",
  },
  {
    index: 30,
    start: "16:25",
    end: "17:05",
    band: "Vowws",
    stage: "ritual",
  },
  {
    index: 31,
    start: "17:55",
    end: "18:45",
    band: "Death Angel",
    stage: "ritual",
  },
  {
    index: 32,
    start: "19:35",
    end: "20:25",
    band: "Municipal Waste",
    stage: "ritual",
  },
  {
    index: 33,
    start: "22:05",
    end: "23:15",
    band: "Heredeiros da Crus",
    stage: "ritual",
  },
  {
    index: 34,
    start: "01:10",
    end: "02:20",
    band: "Hämatom",
    stage: "ritual",
  },
  {
    index: 35,
    start: "15:45",
    end: "16:20",
    band: "Not Yet",
    stage: "chaos",
  },
  {
    index: 36,
    start: "17:05",
    end: "17:55",
    band: "Empire of Disease",
    stage: "chaos",
  },
  {
    index: 37,
    start: "18:45",
    end: "19:30",
    band: "Guilt Trip",
    stage: "chaos",
  },
  {
    index: 38,
    start: "20:50",
    end: "21:50",
    band: "Cabal",
    stage: "chaos",
  },
  {
    index: 39,
    start: "23:15",
    end: "00:15",
    band: "Evergreen Terrace",
    stage: "chaos",
  },
  {
    index: 40,
    start: "01:10",
    end: "02:20",
    band: "Deez Nuts",
    stage: "chaos",
  },
  {
    index: 41,
    start: "15:05",
    end: "15:40",
    band: "We All Fall",
    stage: "desert",
  },
  {
    index: 42,
    start: "16:20",
    end: "17:05",
    band: "SECRET SHOW",
    stage: "desert",
  },
  {
    index: 43,
    start: "17:55",
    end: "18:45",
    band: "Messa",
    stage: "desert",
  },
  {
    index: 44,
    start: "19:35",
    end: "20:35",
    band: "Conan",
    stage: "desert",
  },
  {
    index: 45,
    start: "22:05",
    end: "23:15",
    band: "El Altar del Holocausto",
    stage: "desert",
  },
  {
    index: 46,
    start: "23:55",
    end: "01:10",
    band: "Eagles of Death Metal",
    stage: "desert",
  },
];
