export const WEDNESDAY = [
  {
    index: 1,
    start: "16:00",
    end: "16:40",
    band: "From Fall To Spring",
    stage: "main",
  },
  {
    index: 2,
    start: "17:20",
    end: "18:05",
    band: "Signs of the Swarm",
    stage: "main",
  },
  {
    index: 3,
    start: "18:50",
    end: "19:35",
    band: "Novelists",
    stage: "main",
  },
  {
    index: 4,
    start: "20:25",
    end: "21:25",
    band: "Jinjer",
    stage: "main",
  },
  {
    index: 5,
    start: "22:30",
    end: "00:00",
    band: "Judas Priest",
    stage: "main",
  },
  {
    index: 6,
    start: "01:10",
    end: "02:20",
    band: "Kanonfieber",
    stage: "main",
  },
  {
    index: 7,
    start: "16:40",
    end: "17:20",
    band: "Deimocracy",
    stage: "ritual",
  },
  {
    index: 8,
    start: "18:05",
    end: "18:50",
    band: "Psilicon Flesh",
    stage: "ritual",
  },
  {
    index: 9,
    start: "19:35",
    end: "20:25",
    band: "Lost Society",
    stage: "ritual",
  },
  {
    index: 10,
    start: "21:25",
    end: "22:15",
    band: "Skynd",
    stage: "ritual",
  },
  {
    index: 11,
    start: "00:00",
    end: "01:10",
    band: "Tarja",
    stage: "ritual",
  },
  {
    index: 12,
    start: "16:35",
    end: "17:25",
    band: "letlive.",
    stage: "chaos",
  },
  {
    index: 13,
    start: "18:05",
    end: "18:50",
    band: "Spy",
    stage: "chaos",
  },
  {
    index: 14,
    start: "19:35",
    end: "20:25",
    band: "Paerish",
    stage: "chaos",
  },
  {
    index: 15,
    start: "21:15",
    end: "22:00",
    band: "Terminal Sleep",
    stage: "chaos",
  },
  {
    index: 16,
    start: "23:00",
    end: "00:00",
    band: "House of Protection",
    stage: "chaos",
  },
  {
    index: 17,
    start: "01:10",
    end: "02:10",
    band: "Stick To Your Guns",
    stage: "chaos",
  },
  {
    index: 18,
    start: "16:00",
    end: "16:35",
    band: "Mind Traveller",
    stage: "desert",
  },
  {
    index: 19,
    start: "17:20",
    end: "18:05",
    band: "Travo",
    stage: "desert",
  },
  {
    index: 20,
    start: "18:50",
    end: "19:35",
    band: "Årabrot",
    stage: "desert",
  },
  {
    index: 21,
    start: "20:25",
    end: "21:15",
    band: "The Southern River Band",
    stage: "desert",
  },
  {
    index: 22,
    start: "22:00",
    end: "23:00",
    band: "Eihwar",
    stage: "desert",
  },
  {
    index: 23,
    start: "00:00",
    end: "01:10",
    band: "Pentagram",
    stage: "desert",
  },
];
